# -*- coding: utf-8 -*-
"""oportunidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmF5o0dBf_8kSjIirwPKtQ89evC9EXEJ
"""

# -*- coding: utf-8 -*-
# -----------------------------------------------------
# MODELO HOOKE TRADING – ENTRY RADAR (ALTA VOLATILIDAD)
# -----------------------------------------------------

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# -----------------------------------------------------
# CONFIGURACIÓN
# -----------------------------------------------------
st.set_page_config(page_title="Hooke Trading – Opportunity Radar", layout="wide")

TICKERS = ["GAPB.MX","SPY", "GRUMAB.MX", "IAU",  "NVDA","WALMEX.MX","QUBT", "QTUM", 
"GMEXICOB.MX", "AVGO", "ASURB.MX", "QBTS" , "^GSPC","BTC-USD", "NVDA", "BABA", "VISTAA.MX", "DANHOS13.MX", "EDUCA18.MX",
"FIBRAMQ12.MX", "FIBRAPL14.MX", "FIHO12.MX", "FINN13.MX", "FMTY14.MX",
"FPLUS16.MX", "FSHOP13.MX", "FUNO11.MX", "ACCELSAB.MX", "AGUA.MX", "ALFAA.MX",
"ASURB.MX", "CADUA.MX", "CERAMICB.MX", "DINEB.MX", "GAPB.MX", "GCARSOA1.MX",
"GISSAA.MX", "GMD.MX", "GMXT.MX", "HOMEX.MX", "JAVER.MX", "KUOB.MX",
"OMAB.MX", "ORBIA.MX", "PASAB.MX", "PINFRAL.MX", "SITES1A-1.MX", "TMMA.MX",
"TRAXIONA.MX", "VESTA.MX", "VINTE.MX", "VOLARA.MX", "ALPEKA.MX", "AUTLANB.MX",
"CEMEXCPO.MX", "CMOCTEZ.MX", "COLLADO.MX", "CONVERA.MX", "CYDSASAA.MX",
"GCC.MX", "GMEXICOB.MX", "ICHB.MX", "LAMOSA.MX", "MFRISCOA-1.MX",
"PE&OLES.MX", "POCHTECB.MX", "SIMECB.MX", "TEAKCPO.MX", "VITROA.MX",
"AC.MX", "BIMBOA.MX", "CHDRAUIB.MX", "CUERVO.MX", "CULTIBAB.MX",
"FEMSAUBD.MX", "GIGANTE.MX", "GRUMAB.MX", "HERDEZ.MX", "KIMBERA.MX",
"KOFUBL.MX", "LACOMERUBC.MX", "MINSAB.MX", "SORIANAB.MX", "WALMEX.MX",
"BEVIDESB.MX", "FRAGUAB.MX", "LABB.MX", "MEDICAB.MX", "AMXB.MX",
"AXTELCPO.MX", "CABLECPO.MX", "CTAXTELA.MX", "MEGACPO.MX", "TLEVISACPO.MX",
"ACTINVRB.MX", "BBAJIOO.MX", "BOLSAA.MX", "CREAL.MX", "FINAMEXO.MX",
"FINDEP.MX", "GBMO.MX", "GENTERA.MX", "GFINBURO.MX", "GFNORTEO.MX",
"GNP.MX", "GPROFUT.MX", "INVEXA.MX", "PROCORPB.MX", "Q.MX", "RA.MX",
"AGUILASCPO.MX", "ALSEA.MX", "CIDMEGA.MX", "CIEB.MX", "CMRB.MX",
"HCITY.MX", "HOTEL.MX", "LIVEPOL1.MX", "NEMAKA.MX", "POSADASA.MX",
"RLHA.MX", "SPORTS.MX", "VASCONI.MX", "ARKB", "BTCW", "BTCO", "BITB",
"HODL", "EZBC", "FBTC", "BRRR", "GBTC", "DEFI", "IBIT", "ACWI",
"SPY", "FAS", "SPXL", "TECL", "IAU", "NU", "MELI", "META",
"JPM","NFLX", "IONQ", "RGTI", "PLTR", "SOFI", "HOOD", "FRES.MX", "MCHI", "INDA", "TSM", "AMD", "GOOGL", "AMZN","V"
]

st.image("shop.png", width=280)
st.title("📡 Entry Opportunity Radar")
st.caption("Alta volatilidad · mayor margen · paciencia estratégica")

# -----------------------------------------------------
# PARÁMETROS DEL MODELO
# -----------------------------------------------------
window_ma = 10
elasticidad = 1.5

# -----------------------------------------------------
# FUNCIÓN PRINCIPAL
# -----------------------------------------------------
def analizar_ticker(ticker):
    try:
        df = yf.download(
            ticker,
            period="2y",
            interval="1d",
            auto_adjust=True,
            progress=False
        )
    except Exception:
        return None

    if df is None or df.empty or len(df) < window_ma + 10:
        return None

    # FIX MultiIndex
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    if "Close" not in df.columns:
        return None

    # Medias móviles
    df["MA5"] = df["Close"].rolling(5).mean()
    df["MA10"] = df["Close"].rolling(window_ma).mean()
    df.dropna(inplace=True)

    if df.empty:
        return None

    # Modelo Hooke
    df["x"] = df["Close"] - df["MA10"]
    threshold = df["x"].std() * elasticidad

    if threshold <= 0 or np.isnan(threshold):
        return None

    x_actual = df["x"].iloc[-1]

    # 🔴 SOLO EXTENSIONES BAJISTAS
    if x_actual >= 0:
        return None

    # Tendencia previa bajista (condición de pre-entry)
    tendencia_ok = df["MA5"].iloc[-1] < df["MA10"].iloc[-1]
    if not tendencia_ok:
        return None

    # Margen de oportunidad (qué tan lejos está del entry)
    margen_oportunidad = abs(x_actual) / threshold

    return {
        "Ticker": ticker,
        "Precio actual": float(df["Close"].iloc[-1]),
        "x actual": float(x_actual),
        "Umbral": float(threshold),
        "Margen_Oportunidad": float(margen_oportunidad)
    }

# -----------------------------------------------------
# PROCESAMIENTO
# -----------------------------------------------------
st.info("🔄 Analizando activos bajo régimen de alta volatilidad...")

resultados = []

for t in TICKERS:
    data = analizar_ticker(t)
    if data:
        resultados.append(data)

df_screen = pd.DataFrame(resultados)

if df_screen.empty:
    st.warning("⚠️ No hay activos con extensión bajista suficiente.")
    st.stop()

# -----------------------------------------------------
# RANKING (LOS MÁS ALEJADOS PRIMERO)
# -----------------------------------------------------
df_screen = df_screen.sort_values(
    by="Margen_Oportunidad",
    ascending=False
).reset_index(drop=True)

df_screen.insert(0, "Ranking", df_screen.index + 1)

# -----------------------------------------------------
# ALERTAS POR MARGEN (NO POR CERCANÍA)
# -----------------------------------------------------
def semaforo_vol(x):
    if x >= 0.85:
        return "🟢 OPORTUNIDAD ALTA"
    elif x >= 0.65:
        return "🟡 EN RADAR"
    else:
        return "🔴 AÚN CERCANO"

df_screen["Estado"] = df_screen["Margen_Oportunidad"].apply(semaforo_vol)

# Alertas reales (las lejanas, no las críticas)
oportunidades = df_screen[df_screen["Margen_Oportunidad"] >= 0.85]

if not oportunidades.empty:
    st.success("🎯 ACTIVOS CON ALTO MARGEN DE OPORTUNIDAD 🎯")
    for _, row in oportunidades.iterrows():
        st.markdown(
            f"""
            **{row['Ticker']}**
            - Precio actual: `{row['Precio actual']:.2f}`
            - x actual: `{row['x actual']:.4f}`
            - Margen de oportunidad: `{row['Margen_Oportunidad']:.2f}`
            """
        )
else:
    st.info("ℹ️ No hay activos suficientemente alejados del entry")

# -----------------------------------------------------
# TABLA FINAL
# -----------------------------------------------------
st.subheader("Ranking por margen de oportunidad (Alta Volatilidad)")

st.dataframe(
    df_screen[
        [
            "Ranking",
            "Ticker",
            "Precio actual",
            "x actual",
            "Umbral",
            "Margen_Oportunidad",
            "Estado"
        ]
    ],
    use_container_width=True
)

# -----------------------------------------------------
# ESTILO
# -----------------------------------------------------
st.markdown("""
<style>
    .stApp {
        background-color: #5BF58E;
    }
    h1, h2, h3 {
        color: #000000;
    }
</style>
""", unsafe_allow_html=True)

st.caption("Ranking 1 = activo MÁS alejado del entry por abajo · mayor margen de compra")
